param_grid:
  var_smoothing: 
    - 1e-9
    - 0.1
    - 0.001
    - 0.5
    - 0.05
    - 0.01
    - 1e-8
    - 1e-7
    - 1e-6
    - 1e-10
    - 1e-11

param_grid_xgboost:
  n_estimators:
    - 50
    - 100
    - 130
  max_depth: 
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  random_state:
    - 0
    - 50
    - 100