artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: data/default of credit card clients.xls
  local_data_file: artifacts/data_ingestion/data.xls
  unzip_dir: artifacts/data_ingestion
  file_name: data.csv

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  null_val_path: artifacts/data_ingestion/null_values.csv