artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: data/default of credit card clients.xls
  local_data_file: artifacts/data_ingestion/data.xls
  unzip_dir: artifacts/data_ingestion
  file_name: data.csv

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  null_val_path: artifacts/data_ingestion/null_values.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  model_kmeans_name: model_kmeans.pkl
  model_xabost_name: model_xabost.pkl
  elbow_png: artifacts/elbow.png
  model_dir: artifacts/model_trainer/models

model_prediction:
  root_dir: artifacts/model_prediction
  predict_default_data_path: data/default_predict/default.csv
  predict_data_path: artifacts/model_prediction/data
  predict_validation_status_file: artifacts/model_prediction/status.txt
  predict_kmeans_model_path: artifacts/model_trainer/model_kmeans.pkl
  model_path: artifacts/model_trainer/models
  prediction_output: artifacts/model_prediction/output